Repository anyanyaa/project-x, pull requests merged in 2022-04, with the labels that each got.

#2 Feature/homepage
  .DS_Store
  .gitignore
  package-lock.json
  package.json
  src/.DS_Store
  src/img/.DS_Store
  src/img/black-slider.png
  src/img/car-clock-icon.svg
  src/img/car-icon.svg
  src/img/card-icon.svg
  src/img/cheese-pizza.jpg
  src/img/delivery-map.jpg
  src/img/facebook-logo.svg
  src/img/footer-logo-ppf.svg
  src/img/footer-logo.svg
  src/img/laptop-icon.svg
  src/img/left-arr.svg
  src/img/logo-1.png
  src/img/margarita-pizza.jpg
  src/img/mashroom-pizza.jpg
  src/img/mastercard-footer.png
  src/img/mess-logo.svg
  src/img/novelty-pizza.png
  src/img/pizza-man.png
  src/img/pp-footer.png
  src/img/promo.jpg
  src/img/seasons-pizza.jpg
  src/img/skype-logo.svg
  src/img/star.svg
  src/img/tg-logo.svg
  src/img/viber-logo.svg
  src/img/visa-footer.svg
  src/img/visa.png
  src/img/vk-logo.svg
  src/img/watsapp-logo.svg
  src/img/yandex-circle.svg
  src/img/yellow-slider.png
  src/index.html
  src/scss/.DS_Store
  src/scss/general.scss
  src/scss/pages/.DS_Store
  src/scss/pages/index/catalog.scss
  src/scss/pages/index/delivery.scss
  src/scss/pages/index/footer.scss
  src/scss/pages/index/header.scss
  src/scss/pages/index/promo.scss
  src/scss/reset.scss
  src/scss/styles.scss
Labels: do not merge

#10 Setup webpack
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  gulpfile.js
  package-lock.json
  package.json
  server.js
  src/index.html
  src/index.js
  webpack.config.js
Labels: needs review

#16 Feature/pits 6
  src/.DS_Store
  src/img/.DS_Store
  src/img/left-arr.svg
  src/img/noodle-fone-girl-big.png
  src/img/promo-card-1.svg
  src/img/promo-card-10.svg
  src/img/promo-card-11.svg
  src/img/promo-card-2.svg
  src/img/promo-card-3.svg
  src/img/promo-card-4.svg
  src/img/promo-card-5.svg
  src/img/promo-card-6.svg
  src/img/promo-card-7.svg
  src/img/promo-card-8.svg
  src/img/promo-card-9.svg
  src/promotions.html
  src/scss/.DS_Store
  src/scss/mixins.scss
  src/scss/pages/.DS_Store
  src/scss/pages/promotions/promo-cards.scss
  src/scss/styles.scss
  webpack.config.js
Labels: approved

#15 Add lefthook
  lefthook.yml
  package-lock.json
  package.json
Labels: needs review
